// Registers skeleton bones per page instead of all at once.
//
// registry.ts (generated by `npm run boneyard:build`) imports every bone file,
// and importing it from main.ts put all of them in the entry chunk. Each page
// now registers only its own bones from the module that renders them, matched
// by file name so newly captured bones are picked up without editing this.
//
// Registration must run before a <Skeleton> sets up: the registry is a plain
// Map read inside a computed, so a bone registered later is never seen. A
// module-level call in the view's own import graph guarantees that.
import { registerBones } from 'boneyard-js/vue'

/** Registers an `import.meta.glob(..., { eager: true, import: 'default' })` result. */
export function registerBoneFiles(files: Record<string, unknown>): void {
  registerBones(Object.fromEntries(
    Object.entries(files).map(([path, bones]) => [
      // ./gallery-card-new_role-101.bones.json -> gallery-card-new_role-101,
      // the same key the generated registry uses.
      path.replace(/^.*\//, '').replace(/\.bones\.json$/, ''),
      bones,
    ]),
  ) as Parameters<typeof registerBones>[0])
}
