// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/vue'

import _home_hero from './home-hero.bones.json'
import _home_research_interests from './home-research-interests.bones.json'
import _home_experience from './home-experience.bones.json'
import _home_education from './home-education.bones.json'
import _gallery_card_workshop_IDEAS_TIH_01 from './gallery-card-workshop-IDEAS-TIH-01.bones.json'
import _gallery_card_academic_milestone_01 from './gallery-card-academic_milestone-01.bones.json'
import _gallery_card_academic_milestone_02 from './gallery-card-academic_milestone-02.bones.json'
import _gallery_card_guest_event_01 from './gallery-card-guest_event-01.bones.json'
import _gallery_card_workshop_06 from './gallery-card-workshop-06.bones.json'
import _gallery_card_workshop_05 from './gallery-card-workshop-05.bones.json'
import _gallery_card_academic_milestone_03 from './gallery-card-academic_milestone-03.bones.json'
import _gallery_card_new_role_01 from './gallery-card-new_role-01.bones.json'
import _gallery_card_workshop_04 from './gallery-card-workshop-04.bones.json'
import _gallery_card_workshop_03 from './gallery-card-workshop-03.bones.json'
import _gallery_card_new_role_02 from './gallery-card-new_role-02.bones.json'
import _gallery_card_workshop_02 from './gallery-card-workshop-02.bones.json'
import _gallery_card_workshop_09 from './gallery-card-workshop-09.bones.json'
import _gallery_card_event_01 from './gallery-card-event-01.bones.json'
import _gallery_card_workshop_08 from './gallery-card-workshop-08.bones.json'
import _gallery_card_tech_fest_03 from './gallery-card-tech_fest-03.bones.json'
import _gallery_card_meetup_05 from './gallery-card-meetup-05.bones.json'
import _gallery_card_tech_fest_02 from './gallery-card-tech_fest-02.bones.json'
import _gallery_card_workshop_01 from './gallery-card-workshop-01.bones.json'
import _gallery_card_tech_fest_01 from './gallery-card-tech_fest-01.bones.json'
import _gallery_card_meetup_01 from './gallery-card-meetup-01.bones.json'

registerBones({
  "home-hero": _home_hero,
  "home-research-interests": _home_research_interests,
  "home-experience": _home_experience,
  "home-education": _home_education,
  "gallery-card-workshop-IDEAS-TIH-01": _gallery_card_workshop_IDEAS_TIH_01,
  "gallery-card-academic_milestone-01": _gallery_card_academic_milestone_01,
  "gallery-card-academic_milestone-02": _gallery_card_academic_milestone_02,
  "gallery-card-guest_event-01": _gallery_card_guest_event_01,
  "gallery-card-workshop-06": _gallery_card_workshop_06,
  "gallery-card-workshop-05": _gallery_card_workshop_05,
  "gallery-card-academic_milestone-03": _gallery_card_academic_milestone_03,
  "gallery-card-new_role-01": _gallery_card_new_role_01,
  "gallery-card-workshop-04": _gallery_card_workshop_04,
  "gallery-card-workshop-03": _gallery_card_workshop_03,
  "gallery-card-new_role-02": _gallery_card_new_role_02,
  "gallery-card-workshop-02": _gallery_card_workshop_02,
  "gallery-card-workshop-09": _gallery_card_workshop_09,
  "gallery-card-event-01": _gallery_card_event_01,
  "gallery-card-workshop-08": _gallery_card_workshop_08,
  "gallery-card-tech_fest-03": _gallery_card_tech_fest_03,
  "gallery-card-meetup-05": _gallery_card_meetup_05,
  "gallery-card-tech_fest-02": _gallery_card_tech_fest_02,
  "gallery-card-workshop-01": _gallery_card_workshop_01,
  "gallery-card-tech_fest-01": _gallery_card_tech_fest_01,
  "gallery-card-meetup-01": _gallery_card_meetup_01,
})
